version: "3"
services:
    web:
        image: bastardd666/passwordsharing:web
        container_name: web
        build: 
            context: ./
            dockerfile: ./Dockerfiles/src/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - elastic
            - consul
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    unit:
        image: bastardd666/passwordsharing:unit
        container_name: unittests
        build: 
            context: ./
            dockerfile: ./Dockerfiles/unit/Dockerfile
    api:
        image: bastardd666/passwordsharing:api
        container_name: apitests
        build: 
            context: ./
            dockerfile: ./Dockerfiles/api/Dockerfile
        depends_on: 
            - redis
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    redis:
        image: "redis"
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        ports:
            - "9200:9200"
            - "9300:9300"
        hostname: elastic
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.4.0
        container_name: kibana
        environment: 
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on: 
            - elastic
    consul:
        image: bitnami/consul:latest
        volumes:
            - consuldata:/bitnami
        hostname: consul
        container_name: consul
        ports:
            - '8300:8300'
            - '8301:8301'
            - '8301:8301/udp'
            - '8500:8500'
            - '8600:8600'
            - '8600:8600/udp'
    fabio:
        image: fabiolb/fabio
        volumes:
            - ./Dockerfiles/fabio/fabio.properties:/etc/fabio/fabio.properties
            - fabiodata:/etc/fabio:ro
        container_name: fabio
        ports:
            - "9998:9998"
            - "9999:9999"


volumes:
    esdata:
        driver: local
    consuldata:
    fabiodata:
    redis: